#!/bin/bash

# Prevents accidentally clobbering files.
alias rm='rm -iv'
alias cp='cp -iv'
alias mv='mv -iv'

# Dir utils
alias mkdir='mkdir -pv'
alias ..='cd ..'
alias ...='cd ../..'

# Ls
alias ll='ls -lG'
alias la='ls -AG'
alias lla='ls -lAG'

# Grep
alias grep='grep --color'

# Json formatting
alias jsonf='python -m json.tool'

# Git
alias gl='git log --oneline -15'
alias gl2='git log --oneline -30'
alias gl3='git log --oneline -60'
alias gs='git status'
alias gb='git branch -a'
alias gd='git diff'
alias glp='git log --patch'
alias gsta='git stash apply'
alias gstl='git stash list'
alias gsts='git stash save'
alias gstd='git stash drop'

# Tmux
alias txa='tmux attach'
alias txn='tmux new -s'
alias txl='tmux ls'

# Conda
alias cie="conda info --envs"

# Terminal
alias c="clear"

# Edit shortcuts
alias vimrc="${EDITOR:-vi} ~/.vimrc"
alias sshconfig="${EDITOR:-vi} ~/.ssh/config"
alias tmuxc="${EDITOR:-vi} ~/.tmux.conf"
alias gitconfig="${EDITOR:-vi} ~/.gitconfig"
