#!/bin/bash

function bashrc()
{
    ${EDITOR:-vi} ~/.bashrc
    source ~/.bashrc
    echo "Bash config edited and reloaded."
}

function aliases()
{
    ${EDITOR:-vi} ~/.aliases
    source ~/.aliases
    echo "Aliases edited and reloaded."
}

function functions()
{
    ${EDITOR:-vi} ~/.functions
    source ~/.functions
    echo "Functions edited and reloaded."
}

# Utils
# Syntax: "repeat [X] [command]"
function repeat()
{
    local i max
    max=$1; shift;
    for ((i=1; i <= max ; i++)); do  # --> C-like syntax
        eval "$@";
    done
}
